# Composer stores all downloaded packages in the vendor/ directory.
# Do not use the following if the vendor/ directory is committed to
# your git repository.
# cache:
#   paths:
#   - vendor/

# before_script:
#   - docker info
#   # - curl -sL https://get.docker.com | bash
#   # - docker build -t implementation-tests .

stage-redacted-alpine:
  image: docker:dind
  script:
    - docker build -t implementation-tests .
    - docker run implementation-tests sh -c "php --version"

# # We test PHP5.6
# test:5.6:
#   image: php:5.6
#   script:
#   - phpunit --configuration phpunit.xml.dist

# # We test PHP7.0
# test:7.0:
#   image: php:7.0
#   script:
#   - phpunit --configuration phpunit.xml.dist

# # We test PHP7.1
# test:7.0:
#   image: php:7.1
#   script:
#   - phpunit --configuration phpunit.xml.dist

# php-7.2:
#   script:
#   - docker run implementation-tests sh -c "php --version"

# # We test PHP7.2
# test:7.0:
#   image: php:7.2
#   script:
#   - docker run implementation-tests sh -c "php --version"
#   # - phpunit --configuration phpunit.xml.dist

# # We test PHP7.3
# test:7.0:
#   image: php:7.3
#   script:
#   - phpunit --configuration phpunit.xml.dist